[package]
name = "dual-gravity"
version = "0.1.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2018"

[dependencies]
bevy = "0.3.0"
rand = "0.7.3"
serde = { version = "1.0.117", features = ["derive"] }
toml = "0.5.7"
